### ISSUE TITLE
Contribute the Smart Trailer scenario sample workloads

### ISSUE THREAD

**Issue by ladatz** [eclipse-sdv-blueprints/software-orchestration#1]
## Description

The Smart Trailer scenario is a sample use case that we will provide as part of the blueprint. It is built on top of the software stack. 

Overview of the scenario: The system detects that a smart trailer is being connected to the vehicle. A signal is raised to the orchestrator to start up the necessary providers and applications to manage the smart trailer. These include a Digital Twin Provider, which exposes signals from the trailer to higher-level applications, and a Smart Trailer application, which consumes these signals. The provided smart trailer application prints the value of a property it subscribes to, the TrailerWeight.

The code and documentation for these sample workloads should be committed.

**Tasks:**
- [ ] Change the way that the proto files are ingested so that they don't need to be committed to this repository
- [ ] Check in the sample code
- [ ] Build and push the images to a container registry
