### ISSUE TITLE
Host in-vehicle stack container images in a GitHub container registry

### ISSUE THREAD

**Issue by ladatz** [eclipse-sdv-blueprints/software-orchestration#12]
## Description
Host in-vehicle stack container images in a GitHub container registry

## Expected outcome
In-vehicle stack container images can be consumed from a GitHub container registry

## Tasks

- [ ] Build and validate the images for all 4 in-vehicle stack projects 
- [ ] Push images to a container registry
- [ ] Consume images in both orchestrators' implementations
