### ISSUE TITLE
Change license to MIT?

### ISSUE THREAD

**Issue by eriksven** [eclipse-sdv-blueprints/software-orchestration#23]
## Description
The Eclipse SDV Blueprints project is licensed under Apache 2.0 (https://projects.eclipse.org/projects/automotive.sdv-blueprints). Therefore, this software-orchestration repository uses Apache 2.0 as its license too and has an Apache 2.0 license file in the root directory. 

However, as seen in #17 and #20 we received PRs licensed under MIT. 
This leads me to the question whether we want to re-license the Software Orchestration blueprint under the MIT license. 
To my understanding this would require the approval of the people that contributed so far. 
What do you think @ladatz @odra @inf17101 ?

## Expected outcome

Decision whether the Software Orchestration team can and want to license under the MIT license.

## Tasks

- [ ] get approval from people that contributed so far
- [ ] involve Eclipse Foundation
- [ ] change license file in root directoy
- [ ] adapt license headers in content
